# Generated by Django 5.0 on 2024-01-03 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_info_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='censorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=40, null=True)),
                ('centified_by', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie_info',
            name='censor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='movie.censorinfo'),
        ),
    ]
