# Generated by Django 5.0 on 2024-01-03 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_censorinfo_movie_info_censor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie_info',
            name='directed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directed_movies', to='movie.directors'),
        ),
        migrations.AlterField(
            model_name='directors',
            name='name',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='movie_info',
            name='actors',
            field=models.ManyToManyField(null=True, related_name='acted_movies', to='movie.actor'),
        ),
    ]
